import type { Category, CategoryId } from '@/types/calendar';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'study',
    labelJa: '勉強',
    labelEn: 'Study',
    color: '#7C3AED',
    bgColor: 'bg-purple-100 dark:bg-purple-900/30',
    textColor: 'text-purple-700 dark:text-purple-300',
    isDefault: true,
    isVisible: true,
    sortOrder: 0,
  },
  {
    id: 'class',
    labelJa: '授業',
    labelEn: 'Class',
    color: '#2563EB',
    bgColor: 'bg-blue-100 dark:bg-blue-900/30',
    textColor: 'text-blue-700 dark:text-blue-300',
    isDefault: true,
    isVisible: true,
    sortOrder: 1,
  },
  {
    id: 'part_time',
    labelJa: 'バイト',
    labelEn: 'Shift',
    color: '#EA580C',
    bgColor: 'bg-orange-100 dark:bg-orange-900/30',
    textColor: 'text-orange-700 dark:text-orange-300',
    isDefault: true,
    isVisible: true,
    sortOrder: 2,
  },
  {
    id: 'work',
    labelJa: '仕事',
    labelEn: 'Work',
    color: '#DC2626',
    bgColor: 'bg-red-100 dark:bg-red-900/30',
    textColor: 'text-red-700 dark:text-red-300',
    isDefault: true,
    isVisible: true,
    sortOrder: 3,
  },
  {
    id: 'private',
    labelJa: '私用',
    labelEn: 'Private',
    color: '#16A34A',
    bgColor: 'bg-green-100 dark:bg-green-900/30',
    textColor: 'text-green-700 dark:text-green-300',
    isDefault: true,
    isVisible: true,
    sortOrder: 4,
  },
  {
    id: 'move',
    labelJa: '移動',
    labelEn: 'Move',
    color: '#6B7280',
    bgColor: 'bg-gray-100 dark:bg-gray-800',
    textColor: 'text-gray-600 dark:text-gray-400',
    isDefault: true,
    isVisible: true,
    sortOrder: 5,
  },
  {
    id: 'other',
    labelJa: 'その他',
    labelEn: 'Other',
    color: '#9CA3AF',
    bgColor: 'bg-gray-50 dark:bg-gray-800/50',
    textColor: 'text-gray-500 dark:text-gray-400',
    isDefault: true,
    isVisible: true,
    sortOrder: 6,
  },
];

export function getCategoryById(id: CategoryId | string): Category {
  return DEFAULT_CATEGORIES.find((c) => c.id === id) ?? DEFAULT_CATEGORIES[DEFAULT_CATEGORIES.length - 1];
}
